-- MySQL Script generated by MySQL Workbench
-- Mon Jan 13 14:43:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esan-dsg01
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `esan-dsg01` ;

-- -----------------------------------------------------
-- Schema esan-dsg01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esan-dsg01` DEFAULT CHARACTER SET utf8 ;
USE `esan-dsg01` ;

-- -----------------------------------------------------
-- Table `esan-dsg01`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`users` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo_user` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`countries` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `flag_country` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`stadiums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`stadiums` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`stadiums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `logo_stadium` VARCHAR(20) NOT NULL,
  `capacity` INT NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `foundation` DATE NOT NULL,
  `grass_type` VARCHAR(20) NOT NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_stadiums_countries1`
    FOREIGN KEY (`idcountry`)
    REFERENCES `esan-dsg01`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`teams` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `foundation` DATE NOT NULL,
  `president` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `website` VARCHAR(255) NOT NULL,
  `logo_team` VARCHAR(50) NOT NULL,
  `logo_kit_home` VARCHAR(50) NOT NULL,
  `logo_kit_away` VARCHAR(50) NOT NULL,
  `idcountry` INT NOT NULL,
  `idstadium` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_clubs_countries1`
    FOREIGN KEY (`idcountry`)
    REFERENCES `esan-dsg01`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_stadiums1`
    FOREIGN KEY (`idstadium`)
    REFERENCES `esan-dsg01`.`stadiums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table `esan-dsg01`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`players` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(500) NOT NULL,
  `birth_date` DATE NOT NULL,
  `photo_player` VARCHAR(50) NOT NULL,
  `weight` INT NOT NULL,
  `height` INT NOT NULL,
  `position` VARCHAR(20) NOT NULL,
  `favorite_foot` VARCHAR(10) NOT NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_players_countries1`
    FOREIGN KEY (`idcountry`)
    REFERENCES `esan-dsg01`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`managers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`managers` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`managers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `birth_date` DATE NOT NULL,
  `photo_manager` VARCHAR(20) NOT NULL,
  `favorite_tatic` VARCHAR(10) NOT NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_managers_countries1`
    FOREIGN KEY (`idcountry`)
    REFERENCES `esan-dsg01`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`favorites_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`favorites_teams` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`favorites_teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idteam` INT NOT NULL,
  PRIMARY KEY (`id`, `iduser`, `idteam`),
  CONSTRAINT `fk_users_has_clubs_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `esan-dsg01`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_clubs_clubs1`
    FOREIGN KEY (`idteam`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`favorites_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`favorites_players` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`favorites_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idplayer` INT NOT NULL,
  PRIMARY KEY (`id`, `iduser`, `idplayer`),
  CONSTRAINT `fk_users_has_players_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `esan-dsg01`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_players_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`favorites_managers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`favorites_managers` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`favorites_managers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idmanager` INT NOT NULL,
  PRIMARY KEY (`id`, `iduser`, `idmanager`),
  CONSTRAINT `fk_users_has_managers_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `esan-dsg01`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_managers_managers1`
    FOREIGN KEY (`idmanager`)
    REFERENCES `esan-dsg01`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`competitions` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`competitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `competition_type` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `number_journeys` INT NOT NULL,
  `logo_competition` VARCHAR(50) NOT NULL,
  `logo_federation` VARCHAR(50) NOT NULL,
  `logo_trophie` VARCHAR(50) NOT NULL,
  `season` VARCHAR(50) NOT NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_competitions_countries1`
    FOREIGN KEY (`idcountry`)
    REFERENCES `esan-dsg01`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`teams_competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`teams_competitions` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`teams_competitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idteam` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `league_group` VARCHAR(30) NOT NULL,
  `league_title` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`, `idteam`, `idcompetition`),
  CONSTRAINT `fk_clubs_has_competitions_clubs1`
    FOREIGN KEY (`idteam`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clubs_has_competitions_competitions1`
    FOREIGN KEY (`idcompetition`)
    REFERENCES `esan-dsg01`.`competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`players_competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`players_competitions` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`players_competitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idplayer` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `league_title` VARCHAR(30) NOT NULL,
  `individual_title` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`, `idplayer`, `idcompetition`),
  CONSTRAINT `fk_players_has_competitions_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_competitions_competitions1`
    FOREIGN KEY (`idcompetition`)
    REFERENCES `esan-dsg01`.`competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`managers_competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`managers_competitions` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`managers_competitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmanager` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `league_title` VARCHAR(30) NOT NULL,
  `individual_title` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`, `idmanager`, `idcompetition`),
  CONSTRAINT `fk_managers_has_competitions_managers1`
    FOREIGN KEY (`idmanager`)
    REFERENCES `esan-dsg01`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_has_competitions_competitions1`
    FOREIGN KEY (`idcompetition`)
    REFERENCES `esan-dsg01`.`competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`transfers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`transfers` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`transfers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_transfer` DATE NOT NULL,
  `transfer_type` VARCHAR(20) NOT NULL,
  `valor_transfer` FLOAT NOT NULL,
  `idteam_out` INT NOT NULL,
  `idteam_entry` INT NOT NULL,
  `season` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `idteam_out`, `idteam_entry`),
  CONSTRAINT `fk_transfers_clubs1`
    FOREIGN KEY (`idteam_entry`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfers_teams1`
    FOREIGN KEY (`idteam_out`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`games_clashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`games_clashes` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`games_clashes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idteam_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `number_journey` INT NOT NULL,
  `date_game` DATE NOT NULL,
  `time_game` TIME NOT NULL,
  `season` VARCHAR(20) NOT NULL,
  `idstadium` INT NOT NULL,
  PRIMARY KEY (`id`, `idteam_home`, `idteam_away`, `idcompetition`),
  CONSTRAINT `fk_game_clashes_competitions1`
    FOREIGN KEY (`idcompetition`)
    REFERENCES `esan-dsg01`.`competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_clashes_clubs1`
    FOREIGN KEY (`idteam_away`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_clashes_clubs2`
    FOREIGN KEY (`idteam_home`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_clashes_stadiums1`
    FOREIGN KEY (`idstadium`)
    REFERENCES `esan-dsg01`.`stadiums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`players_transfers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`players_transfers` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`players_transfers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idplayer` INT NOT NULL,
  `idtransfer` INT NOT NULL,
  `idteam_out` INT NOT NULL,
  `idteam_entry` INT NOT NULL,
  `contract_date` DATE NOT NULL,
  `valor_actual` FLOAT NOT NULL,
  `number_shirt` INT NOT NULL,
  PRIMARY KEY (`id`, `idplayer`, `idtransfer`, `idteam_out`, `idteam_entry`),
  CONSTRAINT `fk_players_has_transfers_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_transfers_transfers1`
    FOREIGN KEY (`idtransfer` , `idteam_out` , `idteam_entry`)
    REFERENCES `esan-dsg01`.`transfers` (`id` , `idteam_out` , `idteam_entry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`managers_transfers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`managers_transfers` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`managers_transfers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmanager` INT NOT NULL,
  `idtransfer` INT NOT NULL,
  `idteam_out` INT NOT NULL,
  `idteam_entry` INT NOT NULL,
  `contract_date` DATE NOT NULL,
  `valor_actual` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `idmanager`, `idtransfer`, `idteam_out`, `idteam_entry`),
  CONSTRAINT `fk_managers_has_transfers_managers1`
    FOREIGN KEY (`idmanager`)
    REFERENCES `esan-dsg01`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_has_transfers_transfers1`
    FOREIGN KEY (`idtransfer` , `idteam_out` , `idteam_entry`)
    REFERENCES `esan-dsg01`.`transfers` (`id` , `idteam_out` , `idteam_entry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`matchs_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`matchs_results` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`matchs_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `formation_home` VARCHAR(20) NOT NULL,
  `scores_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `formation_away` VARCHAR(20) NOT NULL,
  `scores_away` INT NOT NULL,
  PRIMARY KEY (`id`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`),
  CONSTRAINT `fk_matchs_results_games_clashes1`
    FOREIGN KEY (`idgame_clashe` , `idteam_home` , `idteam_away` , `idcompetition`)
    REFERENCES `esan-dsg01`.`games_clashes` (`id` , `idteam_home` , `idteam_away` , `idcompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`internation_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`internation_teams` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`internation_teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idteam` INT NOT NULL,
  `idplayer` INT NOT NULL,
  `summoned` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `idteam`, `idplayer`),
  CONSTRAINT `fk_teams_has_players_teams1`
    FOREIGN KEY (`idteam`)
    REFERENCES `esan-dsg01`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_has_players_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`favorites_competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`favorites_competitions` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`favorites_competitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  PRIMARY KEY (`id`, `iduser`, `idcompetition`),
  CONSTRAINT `fk_users_has_competitions_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `esan-dsg01`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_competitions_competitions1`
    FOREIGN KEY (`idcompetition`)
    REFERENCES `esan-dsg01`.`competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`players_matchs_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`players_matchs_results` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`players_matchs_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmatch_result` INT NOT NULL,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `idteam_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `idplayer` INT NOT NULL,
  `type_match_result` VARCHAR(10) NOT NULL,
  `number_shirt` INT NOT NULL,
  `initial_eleven` TINYINT NOT NULL,
  `goals_conceded` INT NOT NULL,
  `goals_scored` INT NOT NULL,
  `assist` INT NOT NULL,
  `yellow_card` INT NOT NULL,
  `red_card` INT NOT NULL,
  `minutes_goals` VARCHAR(50) NOT NULL,
  `minutes_assist` VARCHAR(50) NOT NULL,
  `minutes_yellow` VARCHAR(50) NOT NULL,
  `minutes_red` VARCHAR(50) NOT NULL,
  `subs_entry` VARCHAR(50) NOT NULL,
  `subs_out` VARCHAR(50) NOT NULL,
  `rating_perfomance` FLOAT NOT NULL,
  `player_of_macth` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `idmatch_result`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`, `idplayer`),
  CONSTRAINT `fk_players_has_match_results_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_matchs_results_matchs_results1`
    FOREIGN KEY (`idmatch_result` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    REFERENCES `esan-dsg01`.`matchs_results` (`id` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`managers_matchs_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`managers_matchs_results` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`managers_matchs_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmatch_result` INT NOT NULL,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `idteam_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `idmanager` INT NOT NULL,
  `type_match_result` VARCHAR(10) NOT NULL,
  `yellow_card` INT NOT NULL,
  `red_card` INT NOT NULL,
  `minutes_yellow` VARCHAR(50) NOT NULL,
  `minutes_red` VARCHAR(50) NOT NULL,
  `rating_points` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `idmatch_result`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`, `idmanager`),
  CONSTRAINT `fk_managers_has_matchs_results_managers1`
    FOREIGN KEY (`idmanager`)
    REFERENCES `esan-dsg01`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_matchs_results_matchs_results1`
    FOREIGN KEY (`idmatch_result` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    REFERENCES `esan-dsg01`.`matchs_results` (`id` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`players_games_clashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`players_games_clashes` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`players_games_clashes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `idteam_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `idplayer` INT NOT NULL,
  `type_game_clashe` VARCHAR(10) NOT NULL,
  `initial_formation` TINYINT NOT NULL,
  `alternate_formation` TINYINT NOT NULL,
  `punished` TINYINT NOT NULL,
  `accumulation` TINYINT NOT NULL,
  `expulsion` TINYINT NOT NULL,
  `injured` TINYINT NOT NULL,
  `in_doubt` TINYINT NOT NULL
  PRIMARY KEY (`id`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`, `idplayer`),
  CONSTRAINT `fk_players_has_games_clashes_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_games_clashes_games_clashes1`
    FOREIGN KEY (`idgame_clashe` , `idteam_home` , `idteam_away` , `idcompetition`)
    REFERENCES `esan-dsg01`.`games_clashes` (`id` , `idteam_home` , `idteam_away` , `idcompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`managers_games_clashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`managers_games_clashes` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`managers_games_clashes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `idteam_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `idmanager` INT NOT NULL,
  `type_game_clashe` VARCHAR(10) NOT NULL,
  `punished` TINYINT NOT NULL,
  `expulsion` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`, `idmanager`),
  CONSTRAINT `fk_managers_has_games_clashes_managers1`
    FOREIGN KEY (`idmanager`)
    REFERENCES `esan-dsg01`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_games_clashes_games_clashes1`
    FOREIGN KEY (`idgame_clashe` , `idteam_home` , `idteam_away` , `idcompetition`)
    REFERENCES `esan-dsg01`.`games_clashes` (`id` , `idteam_home` , `idteam_away` , `idcompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`players_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`players_statistics` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`players_statistics` (
  `id` INT NOT NULL,
  `idmatch_result` INT NOT NULL,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `idteam_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `idplayer` INT NOT NULL,
  `position` VARCHAR(10) NOT NULL,
  `minutes_played` VARCHAR(10) NOT NULL,
  `defenses` INT NOT NULL,
  `punches` INT NOT NULL,
  `exits` INT NOT NULL,
  `successful_exits` INT NOT NULL,
  `claimed_ai_balls` INT NOT NULL,
  `defenses_in_box` INT NOT NULL,
  `capital_errors` INT NOT NULL,
  `touches_ball` INT NOT NULL,
  `passes_right` INT NOT NULL,
  `passes_right_percentage` FLOAT NOT NULL,
  `crossings` INT NOT NULL,
  `precise_crossings` INT NOT NULL,
  `long_balls` INT NOT NULL,
  `precise_long_balls` INT NOT NULL,
  `cut_balls` INT NOT NULL,
  `shots_saved` INT NOT NULL,
  `interceptions` INT NOT NULL,
  `tackles` INT NOT NULL,
  `dribbling_suffered` INT NOT NULL,
  `floor_duels` INT NOT NULL,
  `won_floor_duels` INT NOT NULL,
  `air_duels` INT NOT NULL,
  `won_air_duels` INT NOT NULL,
  `loss_of_possession` INT NOT NULL,
  `fouls_committed` INT NOT NULL,
  `fouls_suffered` INT NOT NULL,
  `shots_total` INT NOT NULL,
  `shots_inside_box` INT NOT NULL,
  `shots_outside_box` INT NOT NULL,
  `goal_strikes` INT NOT NULL,
  `goal_strikes_out` INT NOT NULL,
  `shots_blocked` INT NOT NULL,
  `dribbling_attempts` INT NOT NULL,
  `successful_dribbling_attempts` INT NOT NULL,
  `offside` INT NOT NULL,
  PRIMARY KEY (`id`, `idmatch_result`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`, `idplayer`),
  CONSTRAINT `fk_players_has_matchs_results_players1`
    FOREIGN KEY (`idplayer`)
    REFERENCES `esan-dsg01`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_matchs_results_matchs_results1`
    FOREIGN KEY (`idmatch_result` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    REFERENCES `esan-dsg01`.`matchs_results` (`id` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esan-dsg01`.`teams_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esan-dsg01`.`teams_statistics` ;

CREATE TABLE IF NOT EXISTS `esan-dsg01`.`teams_statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmatch_result` INT NOT NULL,
  `idgame_clashe` INT NOT NULL,
  `idcompetition` INT NOT NULL,
  `idteam_home` INT NOT NULL,
  `ball_possession_home` FLOAT NOT NULL,
  `goal_opportunities_home` INT NOT NULL,
  `corners_home` INT NOT NULL,
  `counterattacks_home` INT NOT NULL,
  `idteam_away` INT NOT NULL,
  `ball_possession_away` FLOAT NOT NULL,
  `corners_away` INT NOT NULL,
  `goal_opportunities_away` INT NOT NULL,
  `counterattacks_away` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `idmatch_result`, `idgame_clashe`, `idcompetition`, `idteam_home`, `idteam_away`),
  CONSTRAINT `fk_teams_has_matchs_results_matchs_results1`
    FOREIGN KEY (`idmatch_result` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    REFERENCES `esan-dsg01`.`matchs_results` (`id` , `idgame_clashe` , `idcompetition` , `idteam_home` , `idteam_away`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
