INSERT INTO `countries` 
(`id`, `name`, `flag_country`) 
VALUES

('1', 'Portugal', 'portugal.png'),
('2', 'Inglaterra', 'inglaterra.png'),
('3', 'Espanha	', 'espanha.png'),
('4', 'Itália','italia.png'),
('5', 'Alemanha', 'alemanha.png'),
('6', 'Fança', 'franca.png'),
('7', 'Holanda', 'holanda.png'),
('8','Chipre', 'chipre.png'),
('9', 'Argentina', 'argentina.png'),
('10', 'Angola','angola.png'),
('11', 'Albânia', 'albania.png'),
('12', 'Andorra', 'andorra.png'),
('13', 'Arábia Saudita', 'arabia_saudita.png'),
('14', 'Argélia', 'argelia.png'),
('15', 'Arménia', 'armenia.png'),
('16', 'Austrália', 'australia.png'),
('17', 'Austria', 'austria.png'),
('18', 'Azerbaijão', 'azerbeijao.png'),
('19', 'Austrália', 'australia.png'),
('20', 'Bélgica', 'belgica.png'),

('21', 'Brasil', 'brasil.png'),
('22', 'Bielorrússia', 'bielorrussia.png'),
('23', 'Bolívia', 'bolivia.png'),
('24', 'Bósnia e Herzegovina', 'bosnia.png'),
('25', 'Brunei', 'brunei.png'),
('26', 'Bulgária', 'bulgaria.png'),
('27', 'Burkina Faso', 'burquina_faso.png'),
('28', 'Burundi', 'burundi.png'),
('29', 'Croácia', 'croacia.png'),
('30', 'Colômbia', 'colombia.png'),
('31', 'Camarões', 'camaroes.png'),
('32', 'Cabo Verde', 'cabo_verde.png'),
('33', 'Costa de Marfim', 'costa_marfim.png'),
('34', 'Coreia do Sul', 'coreia_sul.png'),
('35', 'Costa Rica', 'costa_rica.png'),
('36', 'Camarões', 'camaroes.png'),
('37', 'Cuba', 'cuba.png'),
('38', 'Curaçao', 'curacao.png'),
('39', 'Dinamarca', 'dinamarca.png'),
('40', 'Equador', 'equador.png'),

('41', 'Estados Unidos', 'usa.png'),
('42', 'Egito', 'egipto.png'),
('43', 'Emirados dos Emirados Árabes Unidos', 'emirados_arabes_unidos.png'),
('44', 'Escócia', 'escocia.png'),
('45', 'Eslováquia', 'eslovaquia.png'),
('46', 'Eslovénia', 'eslovenia.png'),
('47', 'Estónia', 'estonia.png'),
('48', 'Grécia', 'grecia.png'),
('49', 'Gana', 'gana.png'),
('50', 'Gambia', 'gambia.png'),
('51', 'Gabão', 'gabao.png'),
('52', 'Geórgia', 'georgia.png'),
('53', 'Gibraltar', 'gribaltar.png'),
('54', 'Guiné-Bissau', 'guine_bissau.png'),
('55', 'Hungria', 'hungria.png'),
('56', 'Indonésia', 'indonesia.png'),
('57', 'Islândia', 'islandia.png'),
('58', 'Israel', 'israel.png'),
('59', 'Japão', 'japao.png'),
('60', 'Jamaica', 'jamaica.png'),

('61','Jordânia', 'jordania.png'),
('62', 'Letónia', 'letonia.png'),
('63', 'Luxemburgo', 'lexemburgo.png'),
('64','Lituânia', 'lituania.png'),
('65', 'Marrocos', 'marrocos.png'),
('66', 'México', 'mexico.png'),
('67', 'Mali', 'mali.png'),
('68', 'Macedonia', 'macedonia.png'),
('69', 'Moldávia', 'moldavia.png'),
('70','Moçambique', 'mocambique.png'),
('71', 'Nigéria', 'nigeria.png'),
('72', 'Noruega', 'noruega.png'),
('73', 'Paraguai', 'paraguai.png'),
('74', 'Peru', 'peru.png'),
('75', 'Polónia', 'polonia.png'),
('76', 'País de Gales', 'pais_gales.png'),
('77','Kosovo', 'kosovo.png'),
('78','Kuwait', 'kuwait.png'),
('79', 'Rússia', 'russia.png'),
('80', 'Républica  do Congo', 'rg_do_congo.png'),

('81', 'Républica Checa	', 'rp_checa.png'),
('82', 'Romenia','romenia.png'),
('83', 'República da Irlanda', 'irlanda.png'),
('84', 'Suiça', 'suica.png'),
('85', 'Sérvia', 'servia.png'),
('86', 'Senegal', 'senegal.png'),
('87', 'Suécia', 'suecia.png'),
('88', 'África do Sul', 'africa_do_sul.png'),
('89', 'Suécia', 'suecia.png'),
('90','Uruguai', 'uruguai.png'),
('91', 'Ucrânia', 'ucrania.png'),
('92', 'Tunísia', 'tunisia.png'),
('93', 'Turquia','turquia.png'),
('94', 'Venezuela', 'venezuela.png'),
('95','no country', 'no_country.png');